### ISSUE TITLE
Unexpected error: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#132]
This bug appeared with latest developments, certainly as the persister is now using asyncio.

Latest commit to date is affected ( https://github.com/wapiti-scanner/wapiti/commit/26d16d026d90dba4ca04b906de0ed2d8f582e5f4 )

I'm trying to spot the reason of that bug for days now without any success. I added some logs to make sure the eventloop is not overloaded and it doesn't seem to be the case.

Here are some logs bellow.

```
WARNING:root:to_explore queue size: 2333
WARNING:root:1 tasks done, 6 tasks pending
WARNING:root:to_explore queue size: 2334
WARNING:root:1 tasks done, 6 tasks pending
WARNING:root:to_explore queue size: 2334
[!] ConnectError avec l'URL http://www.bne.es/fr/Catalogos/CatalogoAutoridades/index.html
WARNING:root:1 tasks done, 6 tasks pending
WARNING:root:to_explore queue size: 2333
WARNING:root:2 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2332
WARNING:root:2 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2333
WARNING:root:1 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2349
WARNING:root:1 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2348
WARNING:root:1 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2347
WARNING:root:0 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2346
[!] ConnectError avec l'URL http://www.bne.es/eu/Colecciones/Manuscritos/CatalogosImpresos/index.html
WARNING:root:1 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2345
WARNING:root:1 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2344
WARNING:root:1 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2343
WARNING:root:1 tasks done, 5 tasks pending
WARNING:root:to_explore queue size: 2342
WARNING:root:2 tasks done, 4 tasks pending
WARNING:root:current tasks: 5
DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x7fd1025530d0>
DEBUG:aiosqlite:returning exception unable to open database file
Traceback (most recent call last):
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 291, in connect
    await_only(connection),
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 138, in _connect
    self._connection = await future
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 103, in run
    result = function()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 398, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/wapiti", line 34, in <module>
    wapiti_asyncio_wrapper()
  File "/home/devloop/travaux/wapiti-code/wapitiCore/main/wapiti.py", line 1345, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/devloop/travaux/wapiti-code/wapitiCore/main/wapiti.py", line 1320, in wapiti_main
    await wap.browse(stop_event, parallelism=args.tasks)
  File "/home/devloop/travaux/wapiti-code/wapitiCore/main/wapiti.py", line 367, in browse
    await self.persister.save_requests(cache)
  File "/home/devloop/travaux/wapiti-code/wapitiCore/net/sql_persister.py", line 199, in save_requests
    async with self._engine.begin() as conn:
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/ext/asyncio/base.py", line 57, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 516, in start
    await self.conn.start(is_ctxmanager=is_ctxmanager)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 106, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3165, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3244, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3214, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 291, in connect
    await_only(connection),
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib64/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 138, in _connect
    self._connection = await future
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 103, in run
    result = function()
  File "/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/aiosqlite/core.py", line 398, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/14/e3q8)
/home/devloop/.local/share/virtualenvs/wapiti-code-4-BMv2Qy/lib/python3.8/site-packages/httpx/_client.py:1978: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fd102c8bdc0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```

It occurs when scanning big websites (it may be every website when the scan last more than several minutes).

I can reproduce with this one (just browsing the website):

`./bin/wapiti -u http://www.bne.es/  --color --flush-session  --tasks 32 -m ""`

After some time `httpx` report some `ConnectError` while the website seems still ok. The number of tasks is under control so it seems unlikely that the socket wasn't processed in time.

The issue is that sqlite acts like te file .db is missing while it isn't the case. I did check this by calling an `os.path.exists` just before the last line mentionned in the logs.

THe usual suspects:

- Wapiti (of course)
- [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) 
- [aiosqlite](https://github.com/omnilib/aiosqlite/)
- Python asyncio (that already had some issues with async generators like [this one](https://bugs.python.org/issue38013))

I tried to reduce the amount of calls to the persister by buffering requests and flushing them every 10 seconds or 100 requests (that's why you can read `save_requests` instead of `_set_paths` in the logs) but it did not help.

It can happen even with a number of tasks set to 1.

I tried to replicate the problem in a small piece of code but did not succeed.

**Comment by devl00p** [comment]
Tested versions of aiosqlite:

- 0.11.0 => not compatible with sqlalchemy
- 0.12.0 => bug occurs
- 0.13.0 => bug occurs
- 0.14.0 => bug occurs
- 0.15.0 => bug occurs
- 0.16.0 => bug occurs
- 0.17.0 => bug occurs

**Comment by devl00p** [comment]
using sqlalchemy `engine.connect()` instead of `engine.begin()` => no changes

**Comment by devl00p** [comment]
Using uvloop instead og Python's event loop: not better

**Comment by devl00p** [comment]
I reproduced the bug using aiosqlite directly (without sqlalchemy)

```
WARNING:root:1 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2361
WARNING:root:2 tasks done, 3 tasks pending
WARNING:root:to_explore queue size: 2360
[!] ConnectError avec l'URL http://www.bne.es/fr/Servicios/FormacionUsuarios/Salas/index.html
WARNING:root:0 tasks done, 4 tasks pending
WARNING:root:to_explore queue size: 2359
[!] ConnectError avec l'URL http://www.bne.es/fr/Servicios/FormacionUsuarios/Bdh.html
WARNING:root:1 tasks done, 4 tasks pending
WARNING:root:current tasks: 5
DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x7f85d8bb7040>
DEBUG:aiosqlite:returning exception unable to open database file
```

I don't think there are running processes on my computer that would try to access the db file (and therefore blocking it) without me knowing.

**Comment by devl00p** [comment]
Managed to caught and ignore the exception but it then crashed on opening the pkl file with `OSError: [Errno 24] Too many open files`.

I guess too many sockets are being watched in the loop (that's why there are so many `ConnectError`). As we have a limit on the number of concurrent tasks it may be related to `httpx` limits

**Comment by bretfourbe** [comment]
Hi @devl00p !
We probably have the same issue here https://github.com/wapiti-scanner/wapiti/pull/131. 
The error message is : `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: paths`

**Comment by devl00p** [comment]
I went further and it looks like it is related to locks inside `async_analyze`.

At least the lock to fill `_custom_404_codes` as obvously it is the one that will take the most time. Commenting that block I was able to go far further in the exploration.

**Comment by devl00p** [comment]
To sum up:

- when migrated to httpx and asyncio we unleashed httpx by removing limits because of PoolTimeout issues
- removing limit caused Wapiti to open too much file descriptors during large scans, resulting in unexpected behavior and strange error messages (`unable to open database file` for sqlite)
- when setting default limits back to httpx we can make `PoolTimeout` errors disappear if we remove the locked block used for the `_custom_404_codes`
- the `_custom_404_codes` is not used currently so let's just remove the related block now, we will think about a good implementation later
