### ISSUE TITLE
running wapiti fails on Amazon linux

### ISSUE THREAD

**Issue by mahesh-narvar** [wapiti-scanner/wapiti#134]
Downloaded the repo zip and tried the following from the bin folder:

$ ./wapiti -h
Traceback (most recent call last):
  File "./wapiti", line 34, in <module>
    wapiti_asyncio_wrapper()
  File "/usr/local/lib/python3.6/site-packages/wapitiCore/main/wapiti.py", line 1297, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
AttributeError: module 'asyncio' has no attribute 'run'

Installed wapiti3 as per instructions and it is installed in ~/.local/bin and on running see the error:
[jenkins@ip-10-100-155-12 bin]$ ./wapiti -h
Traceback (most recent call last):
  File "./wapiti", line 5, in <module>
    from wapitiCore.main.wapiti import wapiti_asyncio_wrapper
  File "/var/lib/jenkins/.local/lib/python3.8/site-packages/wapitiCore/main/wapiti.py", line 31, in <module>
    from sqlite3 import OperationalError
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

Any help to get this resolved would help. Python 3.8 is installed. I was able to run this on my mac. Thanks.

**Comment by devl00p** [comment]
Hello,

How was Python installed ? It looks like it wasn't compiled with sqlite support.

You should install sqlite development files then recompile Python. See here: https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by tarraschk** [comment]
No answer, let's close the issue :)
