### ISSUE TITLE
Scanning error

### ISSUE THREAD

**Issue by alexr3** [wapiti-scanner/wapiti#155]
Hi!
After successful installation, the following error occurs:

Oops! No translations found for your language... Using english.
Please send your translations for improvements.

Wapiti-3.0.5 (wapiti.sourceforge.io)
Traceback (most recent call last):
  File "C:\Python39\Scripts\wapiti-script.py", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.0.5', 'console_scripts', 'wapiti')())
  File "C:\Python39\lib\site-packages\wapiti3-3.0.5-py3.9.egg\wapitiCore\main\wapiti.py", line 1297, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\wapiti3-3.0.5-py3.9.egg\wapitiCore\main\wapiti.py", line 1271, in wapiti_main
    loop.add_signal_handler(signal.SIGINT, inner_ctrl_c_signal_handler)
  File "C:\Python39\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError

Help me find the error. Thanks!

**Comment by devl00p** [comment]
I guess this is related to Windows. Did you tried to run it inside WSL (Windows Subsystem for Linux) ?

Regards
