### ISSUE TITLE
Exception SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fwininger** [wapiti-scanner/wapiti#219]
```
# Traceback (most recent call last):
#   File "/usr/local/bin/wapiti", line 33, in 
#     sys.exit(load_entry_point('wapiti3==3.0.8', 'console_scripts', 'wapiti')())
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.0.8-py3.9.egg/wapitiCore/main/wapiti.py", line 1385, in wapiti_asyncio_wrapper
#     asyncio.run(wapiti_main())
#   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
#     return loop.run_until_complete(main)
#   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
#     return future.result()
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.0.8-py3.9.egg/wapitiCore/main/wapiti.py", line 1372, in wapiti_main
#     await wap.attack(global_stop_event)
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.0.8-py3.9.egg/wapitiCore/main/wapiti.py", line 520, in attack
#     await attack_module.finish()
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.0.8-py3.9.egg/wapitiCore/attack/mod_ssrf.py", line 199, in finish
#     data = response.json
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.0.8-py3.9.egg/wapitiCore/net/page.py", line 218, in json
#     return literal_eval(self.content)
#   File "/usr/lib/python3.9/ast.py", line 62, in literal_eval
#     node_or_string = parse(node_or_string, mode='eval')
#   File "/usr/lib/python3.9/ast.py", line 50, in parse
#     return compile(source, filename, mode, flags,
#   File "", line 1
#     You are being <a href="https://X.X.X.X/">redirected</a>.
#     ^
# SyntaxError: invalid syntax
# /usr/local/lib/python3.9/dist-packages/httpx-0.21.1-py3.9.egg/httpx/_client.py:2012: UserWarning: Unclosed . See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```

**Comment by bretfourbe** [comment]
I thiink this one is related to https://github.com/wapiti-scanner/wapiti/pull/215
