### ISSUE TITLE
Installing wapiti fails in alpine linux with "ZIP does not support timestamps before 1980"

### ISSUE THREAD

**Issue by Amaelh** [wapiti-scanner/wapiti#225]
# Abstract
Hello, I'm trying out wapiti and noticed that the "pip3 install wapiti" inside an Alpine docker image is only giving me wapiti 3.0.4. 

I thus tryed to manually install the [latest version wapiti3-3.0.9.tar.gz from sourceforge](https://sourceforge.net/projects/wapiti/files/) using the instructions in [INSTALL.md](https://github.com/wapiti-scanner/wapiti/blob/master/INSTALL.md), but installation fails.

# Detailled output

```
opt/wapiti # python3 setup.py  install
running install
running bdist_egg
running egg_info
writing wapiti3.egg-info/PKG-INFO
writing dependency_links to wapiti3.egg-info/dependency_links.txt
writing entry points to wapiti3.egg-info/entry_points.txt
writing requirements to wapiti3.egg-info/requires.txt
writing top-level names to wapiti3.egg-info/top_level.txt
reading manifest file 'wapiti3.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'wapitiCore/language_sources/*.sh'
warning: no previously-included files found matching 'wapitiCore/language_sources/file_list.txt'
adding license file 'LICENSE'
writing manifest file 'wapiti3.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/wapiti-getcookie to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/wapiti to 755
copying wapiti3.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wapiti3.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wapiti3.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wapiti3.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wapiti3.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wapiti3.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/wapiti3-3.0.9-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
Traceback (most recent call last):
  File "/opt/wapiti/setup.py", line 65, in <module>
    setup(
  File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 225, in run
    make_zipfile(self.egg_output, archive_root, verbose=self.verbose,
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 451, in make_zipfile
    visit(z, dirname, files)
  File "/usr/local/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 444, in visit
    z.write(path, p)
  File "/usr/local/lib/python3.10/zipfile.py", line 1728, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/local/lib/python3.10/zipfile.py", line 518, in from_file
    zinfo = cls(arcname, date_time)
  File "/usr/local/lib/python3.10/zipfile.py", line 362, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
/opt/wapiti # date
Mon Dec 27 16:31:53 UTC 2021
/opt/wapiti # 
```

**Comment by devl00p** [comment]
Hello ! I looked at the archive and every file is ok (oldest file is from 2013).

Maybe try to update your setuptools Python package.

Otherwise you can try to update the timestamp of each file in the folder :

`find wapiti/ -exec touch {} \;`

**Comment by devl00p** [comment]
Closing as it seems more related to an external issue. Archive file has correct timestamps
