### ISSUE TITLE
error when running latest version wapiti3 in windows 10

### ISSUE THREAD

**Issue by macken22jorg** [wapiti-scanner/wapiti#236]
hello my friend, first I want to congratulate you because such a good tool that you created has helped me learn more about programming. This time I am writing to you because as much as I try to install the latest version of wapiti3 it does not work for me, I always get this error, my version python is python  3.10

Wapiti 3.0.9 (wapiti.sourceforge.io)
Traceback (most recent call last):
  File "C:\Python310\Scripts\wapiti-script.py", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.0.9', 'console_scripts', 'wapiti')())
  File "C:\Python310\lib\site-packages\wapiti3-3.0.9-py3.10.egg\wapitiCore\main\wapiti.py", line 1385, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\wapiti3-3.0.9-py3.10.egg\wapitiCore\main\wapiti.py", line 1355, in wapiti_main
    loop.add_signal_handler(signal.SIGINT, inner_ctrl_c_signal_handler)
  File "C:\Python310\lib\asyncio\events.py", line 553, in add_signal_handler
    raise NotImplementedError
NotImplementedError

Might you help me? in version 3.0.4 it works perfectly on windows but now that i try to update it it doesn't work anymore.

Does it only work on linux?

**Comment by devl00p** [comment]
Latests versions use signals through asyncio so indeed it can't work on Windows at that time. You should try to run Wapiti using WSL on Windows.

**Comment by macken22jorg** [comment]
ok friend thanks for your answer
