### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by xhylgogo** [wapiti-scanner/wapiti#247]
version:Wapiti-3.0.4
Traceback (most recent call last):
  File "/usr/local/topas/var/config-topas/vulnerability-scan/wapiti/bin/wapiti", line 30, in <module>
    from wapitiCore.main.wapiti import wapiti_main
  File "/usr/local/topas/var/config-topas/vulnerability-scan/wapiti/wapitiCore/main/wapiti.py", line 48, in <module>
    from wapitiCore.net.sqlite_persister import SqlitePersister
  File "/usr/local/topas/var/config-topas/vulnerability-scan/wapiti/wapitiCore/net/sqlite_persister.py", line 30, in <module>
    class SqlitePersister:
  File "/usr/local/topas/var/config-topas/vulnerability-scan/wapiti/wapitiCore/net/sqlite_persister.py", line 38, in SqlitePersister
    BASE_DIR = os.path.join(HOME_DIR, ".wapiti")
  File "/usr/lib64/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by undergroundwires** [comment]
I reproduce this. When I call wapiti binary using `/tools/wapiti/bin/wapiti --version` using `subprocess` from Python I get this error. But when I call it from bash it works as expected. Any ideas @devl00p ?

**Comment by undergroundwires** [comment]
I reproduce this. When I call wapiti binary using `/tools/wapiti/bin/wapiti --version` using `subprocess` from Python I get this error. But when I call it from bash it works as expected. Any ideas @devl00p ? Tested with 3.1.3.
