### ISSUE TITLE
Getting Traceback when trying to execute your example.txt

### ISSUE THREAD

**Issue by hoganje** [wapiti-scanner/wapiti#286]
I am trying to learn how to use wapiti by going through your example.txt file (https://wapiti.sourceforge.io/example.txt). I first tried to execute this on my Kali Linux and then on an Ubuntu, both created the same issue. The follow Tracebacks are generated when I try to execute the first command: 

$wapiti-getcookie -u http://wackopicko/users/login.php -c cookies.json

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1255d9df0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='wackopicko', port=80): Max retries exceeded with url: /users/login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1255d9df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wapiti-getcookie", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.0.4', 'console_scripts', 'wapiti-getcookie')())
  File "/usr/lib/python3/dist-packages/wapitiCore/main/getcookie.py", line 146, in getcookie_main
    page = crawler.get(Request(args.url), follow_redirects=True)
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 123, in inner_wrapper
    raise exception
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 117, in inner_wrapper
    value = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 391, in get
    raise exception
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 378, in get
    response = self._session.get(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='wackopicko', port=80): Max retries exceeded with url: /users/login.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1255d9df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Thanks for looking into this issue!

**Comment by bretfourbe** [comment]
Hi @hoganje, 
The traceback is due to the fact that `wackopicko` is not a valid domain name. You should try with http://testphp.vulnweb.com/ for instance or any application that you are authorized to test. `wapiti-getcookie` allows you to retrieve valid session cookies for an authenticated scan with wapiti but you can start with unauthenticated scan.

**Comment by devl00p** [comment]
closing as not related to wapiti's code
