### ISSUE TITLE
Cannot `--update` modules

### ISSUE THREAD

**Issue by polyedre** [wapiti-scanner/wapiti#305]
Since 3.1.3, running `wapiti --update` fails with the following error:

```txt
Traceback (most recent call last):
  File "/home/lucas/.local/bin/wapiti", line 8, in <module>
    sys.exit(wapiti_asyncio_wrapper())
  File "/home/lucas/.local/lib/python3.8/site-packages/wapitiCore/main/wapiti.py", line 1129, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/lucas/.local/lib/python3.8/site-packages/wapitiCore/main/wapiti.py", line 920, in wapiti_main
    await wap.crawler.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

In the failing line (920), the value of `wap.crawler` is `None`. It seems that the crawler is only initialized at line [1065](https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/main/wapiti.py#L1065).

# Reproduce

```sh
python3 -m pip install wapiti3
wapiti --update
```

**Comment by polyedre** [comment]
It seems that initializing the crawler before the failing line is enough to fix the problem.
