### ISSUE TITLE
ujson module not found, using json

### ISSUE THREAD

**Issue by Jan078** [wapiti-scanner/wapiti#319]
When i try to scan my url with wapiti -u http://${mywebsite}/ 

Wapiti 3.1.3 (wapiti-scanner.github.io)
Traceback (most recent call last):
  File "\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "CPython\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Python\Python310\Scripts\wapiti.exe\__main__.py", line 7, in <module>
  File "Python\Python310\lib\site-packages\wapitiCore\main\wapiti.py", line 1129, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "Python\Python310\lib\site-packages\wapitiCore\main\wapiti.py", line 1099, in wapiti_main
    loop.add_signal_handler(signal.SIGINT, inner_ctrl_c_signal_handler)
  File Python\Python310\lib\asyncio\events.py", line 553, in add_signal_handler
    raise NotImplementedError
NotImplementedError

**Comment by devl00p** [comment]
Hello ! 

The usjon message is just a warning due to a dependency we are using.

The bug you have here is because the `add_signal_handler` is not supported on your OS.

If you are using Windows you should set up WSL (windows subsystem linux) et run wapiti inside it. Windows is not supported by Wapiti directly.
