### ISSUE TITLE
Wapiti crashing with httpcore version 0.16.3

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [wapiti-scanner/wapiti#359]
3 hour ago was new release of httpcore https://github.com/encode/httpcore/tree/0.16.3 which crashed wapiti
```
Traceback (most recent call last):
  File "/tmp/httptest/bin/wapiti", line 5, in <module>
    from wapitiCore.main.wapiti import wapiti_asyncio_wrapper
  File "/tmp/httptest/lib/python3.8/site-packages/wapitiCore/main/wapiti.py", line 29, in <module>
    import httpx
  File "/tmp/httptest/lib/python3.8/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/tmp/httptest/lib/python3.8/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/tmp/httptest/lib/python3.8/site-packages/httpx/_client.py", line 29, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/tmp/httptest/lib/python3.8/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 13, in <module>
    from .http11 import HTTP11Connection
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 44, in <module>
    class HTTP11Connection(ConnectionInterface):
  File "/tmp/httptest/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 140, in HTTP11Connection
    self, event: h11.Event, timeout: Optional[float] = None
AttributeError: module 'h11' has no attribute 'Event'
```
downgrade version to 0.16.2 solve this problem.
I am not user of wapiti, first time to try this instrument ans take this surprise :-) for your attention

**Comment by devl00p** [comment]
Hello, please try with Wapiti 3.1.5 I just released.
