### ISSUE TITLE
SSL Module Error

### ISSUE THREAD

**Issue by LiterallyBlah** [wapiti-scanner/wapiti#363]
Command: sudo wapiti --url "https://blah.com/" --log blah-wapiti.log -f txt -o blah-wapiti.txt -v 2 --color
```
[!] Module ssl seems broken and will be skipped
TypeError
Traceback (most recent call last):

  File "/usr/bin/wapiti", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.1.4', 'console_scripts', 'wapiti')())
    │   │    └ <function importlib_load_entry_point at 0x7f3280d63d90>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.10/site-packages/wapitiCore/main/wapiti.py", line 369, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
    │       │   └ <function wapiti_main at 0x7f327842a9e0>
    │       └ <function run at 0x7f328081ac20>
    └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object wapiti_main at 0x7f3280a0ace0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f32802d0430>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f32802d03a0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f32802d1ea0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f3280561870>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/lib/python3.10/site-packages/wapitiCore/main/wapiti.py", line 356, in wapiti_main
    await wap.attack(global_stop_event)
          │   │      └ <asyncio.locks.Event object at 0x7f3280a49270 [unset]>
          │   └ <function Wapiti.attack at 0x7f32784288b0>
          └ <wapitiCore.controller.wapiti.Wapiti object at 0x7f32785f3fd0>
  File "/usr/lib/python3.10/site-packages/wapitiCore/controller/wapiti.py", line 436, in attack
    attack_modules = await self._load_attack_modules(stop_event, crawler)
                           │    │                    │           └ <wapitiCore.net.crawler.AsyncCrawler object at 0x7f32784c22f0>
                           │    │                    └ <asyncio.locks.Event object at 0x7f3280a49270 [unset]>
                           │    └ <function Wapiti._load_attack_modules at 0x7f3278428550>
                           └ <wapitiCore.controller.wapiti.Wapiti object at 0x7f32785f3fd0>
> File "/usr/lib/python3.10/site-packages/wapitiCore/controller/wapiti.py", line 299, in _load_attack_modules
    mod = import_module("wapitiCore.attack.mod_" + mod_name)
          │                                        └ 'ssl'
          └ <function import_module at 0x7f3280a33f40>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'wapitiCore.attack.mod_ssl'
           │          └ <function _gcd_import at 0x7f3280d63400>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/wapitiCore/attack/mod_ssl.py", line 27, in <module>
    from sslyze.plugins.certificate_info._certificate_utils import get_common_names, extract_dns_subject_alternative_names
  File "/usr/lib/python3.10/site-packages/sslyze/__init__.py", line 88, in <module>
    from sslyze.json.json_output import SslyzeOutputAsJson, ServerScanResultAsJson
  File "/usr/lib/python3.10/site-packages/sslyze/json/json_output.py", line 105, in <module>
    _HttpProxySettingsAsJson = pydantic.dataclasses.dataclass(HttpProxySettings, frozen=True)
                               │        │           │         └ <class 'sslyze.server_setting.HttpProxySettings'>
                               │        │           └ <function dataclass at 0x7f32767d6b90>
                               │        └ <module 'pydantic.dataclasses' from '/usr/lib/python3.10/site-packages/pydantic-1.10.2-py3.10.egg/pydantic/dataclasses.py'>
                               └ <module 'pydantic' from '/usr/lib/python3.10/site-packages/pydantic-1.10.2-py3.10.egg/pydantic/__init__.py'>
  File "/usr/lib/python3.10/site-packages/pydantic-1.10.2-py3.10.egg/pydantic/dataclasses.py", line 231, in dataclass
    return wrap(_cls)
           │    └ <class 'sslyze.server_setting.HttpProxySettings'>
           └ <function dataclass.<locals>.wrap at 0x7f3275d2d480>
  File "/usr/lib/python3.10/site-packages/pydantic-1.10.2-py3.10.egg/pydantic/dataclasses.py", line 207, in wrap
    dc_cls = dataclasses.dataclass(
             │           └ <function dataclass at 0x7f327f940820>
             └ <module 'dataclasses' from '/usr/lib/python3.10/dataclasses.py'>
  File "/usr/lib/python3.10/dataclasses.py", line 1184, in dataclass
    return wrap(cls)
           │    └ <class 'sslyze.server_setting.HttpProxySettings'>
           └ <function dataclass.<locals>.wrap at 0x7f3275d60ca0>
  File "/usr/lib/python3.10/dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           │              │    │     │     │   │      └ False
           │              │    │     │     │   └ False
           │              │    │     │     └ True
           │              │    │     └ True
           │              │    └ True
           │              └ <class 'sslyze.server_setting.HttpProxySettings'>
           └ <function _process_class at 0x7f327f9405e0>
  File "/usr/lib/python3.10/dataclasses.py", line 1077, in _process_class
    raise TypeError(f'Cannot overwrite attribute {fn.__name__} '

TypeError: Cannot overwrite attribute __setattr__ in class HttpProxySettings
```

**Comment by devl00p** [comment]
Hello ! This is a known issue, I'm currently working on it :)

**Comment by LiterallyBlah** [comment]
> Hello ! This is a known issue, I'm currently working on it :)

Thanks :+1:

**Comment by devl00p** [comment]
Should be ok with Wapiti 3.1.5
