### ISSUE TITLE
Upgrade aiocache dependency

### ISSUE THREAD

**Issue by r3naissance** [wapiti-scanner/wapiti#370]
Just a couple weeks ago I was able to run this from the bin directory but now getting the below.

./bin/wapiti -h
```

Traceback (most recent call last):
  File "/opt/wapiti/./bin/wapiti", line 31, in <module>
    from wapitiCore.main.wapiti import wapiti_asyncio_wrapper
  File "/usr/local/lib/python3.10/dist-packages/wapiti3-3.1.5-py3.10.egg/wapitiCore/main/wapiti.py", line 31, in <module>
    from wapitiCore.attack.attack import (all_modules, common_modules)
  File "/usr/local/lib/python3.10/dist-packages/wapiti3-3.1.5-py3.10.egg/wapitiCore/attack/attack.py", line 39, in <module>
    from wapitiCore.net.sql_persister import SqlPersister
  File "/usr/local/lib/python3.10/dist-packages/wapiti3-3.1.5-py3.10.egg/wapitiCore/net/sql_persister.py", line 24, in <module>
    from aiocache import cached
  File "/usr/local/lib/python3.10/dist-packages/aiocache-0.11.1-py3.10.egg/aiocache/__init__.py", line 17, in <module>
    from aiocache.backends.redis import RedisCache
  File "/usr/local/lib/python3.10/dist-packages/aiocache-0.11.1-py3.10.egg/aiocache/backends/redis.py", line 11, in <module>
    AIOREDIS_BEFORE_ONE = aioredis.__version__.startswith("0.")
AttributeError: module 'aioredis' has no attribute '__version__'
```

**Comment by devl00p** [comment]
This bug is not directly related to Wapiti but to aiocache.

You certainly have the redis package installed which cause aiocache to import aioredis, see https://github.com/aio-libs/aiocache/blob/master/aiocache/__init__.py#L18

The access to the __version__ attribute was removed with this commit : https://github.com/aio-libs/aiocache/commit/a2741965fa6bda74680f6a82e90fc053d2c3cd2d#diff-d343e8d4d6f140b9992b916ca117cdb4549de4e0bd36628cc94f2b3627ba2b88

However aiocache 0.11.1 was released in Jul 31, 2019 while a new version was released on Jan 13, 2023 (no versions between the two releases).

I will check if we can use the latest version of aiocache within Wapiti
