### ISSUE TITLE
pip install wapiti fails with NotImplementedError: wapiti Python 3 support en route to your location

### ISSUE THREAD

**Issue by tavdog** [wapiti-scanner/wapiti#423]
I'm on OSX, created venv with python 3.11 then did pip3/pip install wapiti and got 
```
(wapiti_env) tavis@M1Pro ~/c/wapiti_env> pip3 install wapiti
Collecting wapiti
  Using cached wapiti-0.1.tar.gz (38 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/32/539xn9y15y55dj9chf6r7kl40000gn/T/pip-install-rh19mlb0/wapiti_3eced75002cf433eb34a1989b19b9b6d/setup.py", line 28, in <module>
          raise NotImplementedError("wapiti Python 3 support en route to your location")
      NotImplementedError: wapiti Python 3 support en route to your location
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by devl00p** [comment]
Hello,  the pip package is named "wapiti3". Regards

**Comment by tavdog** [comment]
Thanks
