### ISSUE TITLE
RuntimeError in mod_xxe

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#483]
Stumbled into this today:

```
[*] Launching module xxe
Traceback (most recent call last):
  File "wapitiCore/attack/mod_xxe.py", line 394, in finish
    mutated_request, __, __ = next(mutator.mutate(original_request, [used_payload]))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/wapiti", line 34, in <module>
    wapiti_asyncio_wrapper()
  File "wapitiCore/main/wapiti.py", line 395, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "/home/devloop/.pyenv/versions/3.9.15/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/devloop/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "wapitiCore/main/wapiti.py", line 382, in wapiti_main
    await wap.attack(global_stop_event)
  File "wapitiCore/controller/wapiti.py", line 536, in attack
    await attack_module.finish()
RuntimeError: coroutine raised StopIteration
```

It looks like the call to `next` returned nothing while it was expected.

The bug appeared while scanning a Wordpress install with the plugin "addonify-quick-view" but maybe it is possible to spot the bug just by looking at the Wapiti code.

**Comment by bretfourbe** [comment]
Is it possible to enter in the `else` case in `finish` method where `XXEUploadMutator` is called even if there is no `file_params` ? 
https://github.com/wapiti-scanner/wapiti/blob/e076399f887d340e55e17cb009b88f2401460989/wapitiCore/attack/mod_xxe.py#L389-L394
In this specific case, `mutate` will yield nothing.
https://github.com/wapiti-scanner/wapiti/blob/e076399f887d340e55e17cb009b88f2401460989/wapitiCore/attack/attack.py#L504-L511

**Comment by devl00p** [comment]
Indeed and `XXEUploadMutator` is used if the form have the enctype `multipart/form-data` which can happen even if no file upload field is present.

However if we crashed in `finish` it looks like something was triggered so an investigation would be helpful.

Let's keep the issue open till we find a way to reproduce

**Comment by Darkiros** [comment]
I've found a way to reproduce. 
It seems happen when you have only one `file_params` in the request and you put the `--skip` option on that param. 
Then, the for is passed and the yield is never triggered.

https://github.com/wapiti-scanner/wapiti/blob/9aaebe725796f9ce7178baf6d6cf5a3d11ca0207/wapitiCore/attack/attack.py#L509-L517

![image](https://github.com/wapiti-scanner/wapiti/assets/37926502/71806446-d264-4cbb-ac72-adf086672f07)


Test done with with out of bounds payload only and this php file : 

```php
  GNU nano 5.4                      ./upload.php                                
<?php
if (isset($_FILES["calendar"])) {
    libxml_disable_entity_loader(false);
    $dom = new DOMDocument();
    move_uploaded_file($_FILES["calendar"]["tmp_name"], "/dev/shm/wapiti.xml");
    $calendar = file_get_contents("/dev/shm/wapiti.xml");
    $dom->loadXML($calendar, LIBXML_NOENT | LIBXML_DTDLOAD);
    $output = simplexml_import_dom($dom);
    echo "Data loaded.";
} else {
?>
    <form method="POST" enctype="multipart/form-data">
        Please send your xml calendar: <input type="file" name="calendar"/ >
        <input type="submit" value="Submit" />
    </form>
<?php
}
?>
```

Command : `wapiti -u http://127.0.0.1/upload.php -m xxe --skip calendar`

**Comment by devl00p** [comment]
Reproduced and fixed in #784 (merged, commit c38036b) — thanks @Darkiros for the repro, it worked exactly as described once tested against the project's own self-hosted OOB endpoint (`Dockerfile.endpoint`).

`finish()` called `next()` directly on the mutator's generator to rebuild the evil request for the report. When the parameter that triggered the OOB callback is excluded via `--skip`, both `Mutator` and `XXEUploadMutator` yield nothing, so `next()` raised `StopIteration`, which PEP 479 turns into `RuntimeError: coroutine raised StopIteration` and kills the whole scan. Now wrapped in `try/except StopIteration` and the finding is simply skipped (the user explicitly excluded that parameter, so nothing to report on it), with a regression test covering both the upload and regular-parameter mutator branches.
