### ISSUE TITLE
Issue probably related to Asyncio

### ISSUE THREAD

**Issue by saltasatelites** [wapiti-scanner/wapiti#528]
Hello:
This is the result of a simply "python wapiti -u http://192.168.1.1"
It looks related to asyncio. I've all the dependencies up to date.
Running on Archlinux with wapiti installed from sources. Running ok until now.

`Wapiti 3.1.8 (wapiti-scanner.github.io)'

´Traceback (most recent call last):´
  File "/opt/wapiti/bin/wapiti", line 34, in <module>
    wapiti_asyncio_wrapper()
  File "/opt/wapiti/wapitiCore/main/wapiti.py", line 426, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/wapiti/wapitiCore/main/wapiti.py", line 304, in wapiti_main
    if "cms" in args.modules and not args.cms:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

Thanks in advance.

**Comment by tarraschk** [comment]
Got it, @bretfourbe can you take a look?

**Comment by saltasatelites** [comment]
Works perfectly.
Thanks !!
