### ISSUE TITLE
asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by ilqar200** [wapiti-scanner/wapiti#531]
Hi. I have got error in wapiti while scanning .I am using wapiti 3.1.8 in kali linux.  I have started wapiti with command :
`wapiti -u https://website  --flush-session --flush-attacks -v 2` 
Here is error : 
`Traceback (most recent call last):
  File "/usr/local/bin/wapiti", line 8, in <module>
    sys.exit(wapiti_asyncio_wrapper())
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/main/wapiti.py", line 395, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/main/wapiti.py", line 370, in wapiti_main
    await wap.browse(global_stop_event, parallelism=args.tasks)
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/controller/wapiti.py", line 401, in browse
    async for resource, response in explorer.async_explore(self._start_urls, self._excluded_urls):
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/net/explorer.py", line 420, in async_explore
    success, resources, response = await task
                                   ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/net/explorer.py", line 307, in _async_analyze
    response: Response = await self._crawler.async_send(request, stream=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/net/crawler.py", line 386, in async_send
    response = await self.async_get(request, headers=headers,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/net/crawler.py", line 59, in inner_wrapper
    value = await function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wapitiCore/net/crawler.py", line 238, in async_get
    response = await self._client.send(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/anyio/_core/_sockets.py", line 221, in connect_tcp
    await event.wait()
  File "/usr/lib/python3/dist-packages/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
`
How to solve this issue ? thanks.

**Comment by bretfourbe** [comment]
Hi @ilqar200, how did you install wapiti ? Can you provide your `pip freeze` output if installed from github please ?

**Comment by ilqar200** [comment]
> Hi @ilqar200, how did you install wapiti ? Can you provide your `pip freeze` output if installed from github please ?

I have installed wapiti with this command : 
`pip install wapiti3==3.1.8`

**Comment by Slokilla** [comment]
I installed wapiti via pip and was unable to reproduce your error. Is this your first installation of wapiti? Can you run `wapiti --version` to make sure you are running version 3.1.8?

**Comment by ilqar200** [comment]
> I installed wapiti via pip and was unable to reproduce your error. Is this your first installation of wapiti? Can you run `wapiti --version` to make sure you are running version 3.1.8?

Yes it is my first installation of wapiti. Here is screen of i have wapiti 3.1.8.
![screen](https://github.com/wapiti-scanner/wapiti/assets/96200654/554a8f26-6ec7-4958-b8be-95f57f76698c)
