### ISSUE TITLE
AttributeError: module 'bcrypt' has no attribute '__about__' with Python 3.11.9

### ISSUE THREAD

**Issue by LpCodes** [wapiti-scanner/wapiti#621]
C:\Users\zebra>wapiti -u http://target/
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'

     __    __            _ _   _ _____
    / / /\ \ \__ _ _ __ (_) |_(_)___ /
    \ \/  \/ / _` | '_ \| | __| | |_ \
     \  /\  / (_| | |_) | | |_| |___) |
      \/  \/ \__,_| .__/|_|\__|_|____/
                  |_|
Wapiti 3.2.0 (wapiti-scanner.github.io)
[*] You are lucky! Full moon tonight.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Scripts\wapiti.exe\__main__.py", line 7, in <module>
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\site-packages\wapitiCore\main\wapiti.py", line 502, in wapiti_asyncio_wrapper
    asyncio.run(wapiti_main())
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\site-packages\wapitiCore\main\wapiti.py", line 476, in wapiti_main
    loop.add_signal_handler(signal.SIGINT, inner_ctrl_c_signal_handler)
  File "C:\Users\zebra\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 578, in add_signal_handler
    raise NotImplementedError
NotImplementedError

**Comment by devl00p** [comment]
Hello,

this is an issue within passlib, see https://foss.heptapod.net/python-libs/passlib/-/issues/190#notes

However there is not fix available right now. You can try to downgrade passlib.

**Comment by LpCodes** [comment]
any partucular version of passlib to which i can downgrade ?

**Comment by devl00p** [comment]
based on the passlib issue you can try to force bcrypt==4.0.1

**Comment by devl00p** [comment]
closing as new versions of wapiti were released and python 3.11 isn't supported anymore
